# Generated by Django 5.1.4 on 2025-01-04 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='image_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
