# Generated by Django 5.1.4 on 2025-01-04 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_comment_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='count',
        ),
        migrations.AddField(
            model_name='product',
            name='comment_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
