# Generated by Django 5.1.4 on 2025-01-04 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_remove_comment_count_product_comment_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='total_stars',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
