# Generated by Django 5.1.4 on 2024-12-25 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_address_phone_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
