# Generated by Django 5.1.4 on 2024-12-30 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_discountcode_cart_discount_code'),
        ('user', '0005_delete_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='discount_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.discountcode'),
        ),
    ]
