# Generated by Django 5.1.4 on 2025-01-02 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_order_id_alter_order_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountcode',
            name='usage',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='discountcode',
            name='usage_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
